#!/usr/bin/perl
use strict;
use warnings;

#my $out_put_dir;
my $file1=$ARGV[0];
my $file2=$ARGV[1];
my $ref_dir=$ARGV[2];
my $ref=$ARGV[3];
my $gene_model=$ARGV[4];
my $pwd=`pwd`;chomp $pwd;
my $name=$ARGV[5];
my $out_put_dir=$name;
open O,">$pwd/$name.control"||die;
print O "<Files>\n";
print O "$file1\n";
print O "$file2\n";
print O "<Options>\n";
print O "ThreadNumber=1\n";
print O "PairedEnd=True // Possible values: True, False. Default value=False\n";
print O "FileFormat=FASTQ // Possible values: FASTQ, FASTA, QSEQ. Default value=FASTQ\n";
print O "AutoPenalty=True // Possible values: True, False. Default value=True\n";
print O "FixedPenalty=2 // Possible values: 0-100. Default value=2, when AutoPenalty=False\n";
print O "Gzip=True // Possible values: True, False. Default value=False\n";
print O "TrimByQuality=False\n";
print O "ExpressionMeasurement=None // possible values: None, TPM, RPKM, TPM_Transcript, RPKM_Transcript. Default value =None\n";
print O "SearchNovelExonJunction=True // Possible values: True, False. Default value=False\n";
print O "GenerateSamFiles=True // Possible values: True, False. Default value=False\n";
print O "ExpectedInsertSize=200\n";
print O "ExcludeNonUniqueMapping=True\n";
print O "ExcludeUnmappedInBam=True\n";
print O "<Output>\n";
print O "OutputName=$name\n";
print O "OutputPath=$out_put_dir\n";
close O;
#open O2,">$pwd/tmp.$name.sh"||die;
print "mono /home/jhmi/xinli/soft/OSAv4.0.2.1/osa.exe --alignrna $ref_dir $ref $gene_model $pwd/$name.control";
#close O2;
#print "qsub -cwd -l cegs,mf=20G,h_vmem=40G   $pwd/$name.sh\n";
#system("qsub -cwd -l cegs,mf=20G,h_vmem=30G $pwd/$name.sh");
